### Post "Island"

POST http://localhost:8080/cards
Content-Type: application/json

{
  "name": "Island",
  "setCode": "M21",
  "typeId": 0
}

### Get all cards
GET http://localhost:8080/cards

### Get all decks
GET http://localhost:8080/decks

### Get deck cards
GET http://localhost:8080/decks/1

