### Post "Island"

POST http://localhost:8080/cards
Content-Type: application/json

{
  "name": "Plain",
  "setCode": "M21"
}

### Get all cards
GET http://localhost:8080/cards

### Get all decks
GET http://localhost:8080/decks

### Post deck
POST http://localhost:8080/decks
Content-Type: application/json

{
  "name": "New Deck",
  "description": "New description",
  "isShared": 1
}

### Add card to deck
POST http://localhost:8080/decks/1/card/2

### Get deck cards
GET http://localhost:8080/decks/1

### Delete card 
DELETE http://localhost:8080/cards/1