#!/bin/sh
docker run -d --name mtgdb_container -p 5432:5432 -e POSTGRES_PASSWORD=0000 -e POSTGRES_USER=postgres -e POSTGRES_DB=mtgdb postgres:alpine
sleep 10
read -n 1 -s -r -p "Press any key to continue"